Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
AllCops:
  TargetRubyVersion: 2.6
Documentation:
  Enabled: false
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
